import { contextBridge, ipcRenderer } from 'electron';
import type { TokenApi } from '../shared/types';

const api: TokenApi = {
  getState: () => ipcRenderer.invoke('auth:state'),
  getAppInfo: () => ipcRenderer.invoke('app:info'),
  setupAdmin: (username, password, trustDevice) => ipcRenderer.invoke('auth:setup', username, password, trustDevice),
  login: (username, password, trustDevice) => ipcRenderer.invoke('auth:login', username, password, trustDevice),
  logout: () => ipcRenderer.invoke('auth:logout'),
  listUsers: () => ipcRenderer.invoke('users:list'),
  createUser: (username, password, role) => ipcRenderer.invoke('users:create', username, password, role),
  setUserActive: (userId, active) => ipcRenderer.invoke('users:set-active', userId, active),
  changePassword: (userId, password) => ipcRenderer.invoke('users:change-password', userId, password),
  resolveAdminNameConflict: newUsername => ipcRenderer.invoke('users:resolve-admin-name-conflict', newUsername),
  getSourceStatuses: () => ipcRenderer.invoke('sources:statuses'),
  getOnboardingStatus: () => ipcRenderer.invoke('onboarding:status'),
  getCollectionDiagnostics: () => ipcRenderer.invoke('sources:diagnostics'),
  getScanProgress: () => ipcRenderer.invoke('sources:progress'),
  getAccountCollectionStatuses: () => ipcRenderer.invoke('admin:account-statuses'),
  scanSources: () => ipcRenderer.invoke('sources:scan'),
  cancelScan: () => ipcRenderer.invoke('sources:cancel-scan'),
  getSourceIdentities: () => ipcRenderer.invoke('sources:identities'),
  previewSourceBinding: (key, userId, filter) => ipcRenderer.invoke('sources:preview-binding', key, userId, filter),
  confirmSourceBinding: previewId => ipcRenderer.invoke('sources:confirm-binding', previewId),
  cancelSourceBinding: previewId => ipcRenderer.invoke('sources:cancel-binding', previewId),
  getTelemetryConfiguration: () => ipcRenderer.invoke('telemetry:configuration'),
  getServerStatus: () => ipcRenderer.invoke('server:status'),
  configureServer: (url, token, adminToken) => ipcRenderer.invoke('server:configure', url, token, adminToken),
  useBuiltInServer: () => ipcRenderer.invoke('server:use-built-in'),
  getUploadStatus: () => ipcRenderer.invoke('sync:status'),
  retryUpload: () => ipcRenderer.invoke('sync:retry'),
  checkUpdate: () => ipcRenderer.invoke('update:check'),
  downloadUpdate: () => ipcRenderer.invoke('update:download'),
  backupDatabase: () => ipcRenderer.invoke('data:backup'),
  restoreDatabase: () => ipcRenderer.invoke('data:restore'),
  openFilePermissions: () => ipcRenderer.invoke('system:open-file-permissions'),
  submitFeedback: (category, title, message, attachDiagnostics, id) => ipcRenderer.invoke('feedback:submit', category, title, message, attachDiagnostics, id),
  getMyFeedback: () => ipcRenderer.invoke('feedback:my'),
  retryFeedback: () => ipcRenderer.invoke('feedback:retry'),
  listFeedback: () => ipcRenderer.invoke('feedback:list'),
  setFeedbackResolved: (id, resolved) => ipcRenderer.invoke('feedback:set-resolved', id, resolved),
  queryUsage: query => ipcRenderer.invoke('usage:query', query),
  queryUsageDetails: (query, page, period, snapshotId) => ipcRenderer.invoke('usage:details', query, page, period, snapshotId),
  exportCsv: (query, snapshotId) => ipcRenderer.invoke('reports:export-csv', query, snapshotId)
};

contextBridge.exposeInMainWorld('tokenApi', api);
