// Keep these IDs aligned with the canonical traceability workbook in outputs/.
const app = ['e2e', 'tests/e2e/app.spec.ts', '管理员创建、用户管理与普通用户权限'];
const collector = ['unit', 'tests/collector.test.ts'];
const report = ['unit', 'tests/report.test.ts', '报表按本地时区与 ISO 周汇总，并限制普通用户归属'];
const telemetry = ['unit', 'tests/telemetry.test.ts', '本机遥测只接受密钥，Codex 去重，Claude 累计点计算增量，报表避免双来源相加'];
const cases = [
  ['TC-001', 'manual', '本机来源字段抽样', '在当前版本检查可读取的 Codex 与 Claude Code 文件；只记录结构、字段口径、脱敏统计和未知项。'],
  ['TC-002', ...app, '首次创建与重启登录'],
  ['TC-003', 'unit', 'tests/auth.test.ts', '首次管理员、重启后的登录和失败尝试限速', '重复初始化和登录限速'],
  ['TC-004', ...app, '用户创建与权限隔离'],
  ['TC-005', ...app, '管理 IPC 拒绝越权'],
  ['TC-006', 'manual', 'Codex 真实样本逐条核对', '用两段当前版本的只读 Codex 多模型样本独立计算，并与采集结果逐条比对；不复制真实正文到仓库。'],
  ['TC-007', ...collector, '模型切换与 Claude 子代理记录按实际模型归档', 'Codex 模型切换'],
  ['TC-008', 'manual', 'Claude 真实样本逐条核对', '用两段当前版本的只读 Claude 多模型和子代理样本独立计算，并与采集结果逐条比对；不复制真实正文到仓库。'],
  ['TC-009', ...collector, '两个采集器按请求去重，重扫和增量扫描不重复计数', 'Claude 请求重复归并'],
  ['TC-010', ...collector, '两个采集器按请求去重，重扫和增量扫描不重复计数', '重复扫描和重启幂等'],
  ['TC-011', ...collector, '未写完的末行等待补齐，截断重写后不重复统计', '末行、截断与轮转'],
  ['TC-012', ...collector, '两个采集器按请求去重，重扫和增量扫描不重复计数', 'Codex 缓存子集不重加'],
  ['TC-013', ...collector, '两个采集器按请求去重，重扫和增量扫描不重复计数', 'Claude 四类 Token 合计'],
  ['TC-014', ...telemetry, '遥测密钥和监听范围'],
  ['TC-015', 'unit', 'tests/telemetry.test.ts', '遥测配置提示现有用户设置而不修改文件', '现有配置只读检查'],
  ['TC-016', ...telemetry, '遥测幂等和重叠优先级'],
  ['TC-017', 'e2e', 'tests/e2e/source-status.spec.ts', '工具目录缺失、无权限和空目录有清晰状态', '缺失和不可读来源状态'],
  ['TC-018', ...collector, '空目录、错误字段及不可读文件显示可辨认的状态', '无效 Token 字段持续报错'],
  ['TC-019', ...app, '绑定后权限和报表更新'],
  ['TC-020', ...report, '时区和 ISO 跨年周'],
  ['TC-021', ...report, '筛选与分页明细'],
  ['TC-022', ...app, 'CSV 与页面结果一致'],
  ['TC-023', ...report, 'CSV 公式注入转义'],
  ['TC-024', 'unit', 'tests/backup.test.ts', '数据库备份完整性校验并保留账户与用量', '备份完整性'],
  ['TC-025', 'e2e', 'tests/e2e/restore.spec.ts', '管理员备份、恢复后账户回到备份状态', '恢复前副本和状态回退'],
  ['TC-026', ...app, '跨进程权限和数据边界'],
  ['TC-027', 'manual', '未签名 DMG 本机验收', '对本次构建的 DMG 执行 hdiutil verify；挂载并复制 Token.app；在当前 Mac 启动、登录、采集并留存脱敏结果。'],
  ['TC-028', 'manual', '签名公证及目标 Mac 验收', '在已配置 Developer ID 和公证凭据的发布环境运行 npm run pack:signed，核对 release/signed 中的核验记录；随后在另一台目标 Mac 安装，并记录启动、登录、采集和脱敏证据。缺少证书、凭据或目标 Mac 时保持待验证。'],
  ['TC-029', 'unit', 'tests/next-report.test.ts', 'TC-029 CSV 表头和数据列对齐', 'CSV 表头与数据列对齐'],
  ['TC-030', 'unit', 'tests/next-auth.test.ts', 'TC-030 勾选信任后重启恢复且未勾选不恢复', '信任设备恢复登录'],
  ['TC-031', 'unit', 'tests/next-auth.test.ts', 'TC-031 退出停用重置密码撤销受信凭证', '撤销与账户失效'],
  ['TC-032', 'unit', 'tests/next-server.test.ts', 'TC-032 服务默认地址可配置且停服不影响本机数据库', '服务地址与本机数据边界'],
  ['TC-033', 'unit', 'tests/next-server.test.ts', 'TC-033 更新清单与包哈希一致且拒绝路径穿越', '清单与包'],
  ['TC-034', 'unit', 'tests/next-update.test.ts', 'TC-034 只提示较新且架构匹配的版本并校验包摘要', '版本与摘要'],
  ['TC-035', 'unit', 'tests/next-update.test.ts', 'TC-035 停服和下载失败可重试且不留临时包', '服务与下载故障'],
  ['TC-036', 'unit', 'tests/next-update.test.ts', 'TC-036 校验后只交给自动安装器且启动失败时旧版不退出', '自动安装控制与回滚'],
  ['TC-037', 'unit', 'tests/next-sync.test.ts', 'TC-037 启动及十分钟定时扫描并串行执行', '三种扫描触发'],
  ['TC-038', 'unit', 'tests/next-sync.test.ts', 'TC-038 聚合上报只含授权用量字段不含正文路径密钥', '聚合隐私'],
  ['TC-039', 'unit', 'tests/next-sync.test.ts', 'TC-039 重复上报幂等且修订快照替换旧值', '幂等和修订'],
  ['TC-040', 'unit', 'tests/next-sync.test.ts', 'TC-040 停服后待传快照持久化并恢复补传', '离线补传'],
  ['TC-041', 'unit', 'tests/next-report.test.ts', 'TC-041 K M P 1024 进位且原值保留在 CSV', '单位和原值'],
  ['TC-042', 'unit', 'tests/next-report.test.ts', 'TC-042 概览等长区间比较与未知基期', '概览比较'],
  ['TC-043', 'unit', 'tests/next-report.test.ts', 'TC-043 日周月趋势点击下钻保持同一时间桶', '趋势下钻'],
  ['TC-044', 'unit', 'tests/next-report.test.ts', 'TC-044 模型排行总量降序且同值稳定', '模型排行'],
  ['TC-045', 'unit', 'tests/next-report.test.ts', 'TC-045 已覆盖零与未覆盖错误状态分开显示', '零和未知'],
  ['TC-046', 'unit', 'tests/next-report.test.ts', 'TC-046 来源状态和最近扫描时间一致', '来源状态'],
  ['TC-047', 'unit', 'tests/next-server.test.ts', 'TC-047 上报接口鉴权和字段白名单', '接口鉴权'],
  ['TC-048', 'e2e', 'tests/e2e/trend.spec.ts', 'TC-048 趋势图宽窄窗口自适应且数值日期不重叠', '趋势图窗口缩放'],
  ['TC-049', 'e2e', 'tests/e2e/trend.spec.ts', 'TC-049 周横轴显示周一日期月横轴显示年月且下钻一致', '周月日期标签'],
  ['TC-050', 'unit', 'tests/m6-project.test.ts', 'TC-050 Codex cwd 归属与缺失项目保持未知', 'Codex 项目识别'],
  ['TC-051', 'unit', 'tests/m6-project.test.ts', 'TC-051 Claude cwd 和子代理文件独立归属', 'Claude 项目识别'],
  ['TC-052', 'unit', 'tests/m6-project.test.ts', 'TC-052 同名路径不合并且外发摘要无项目标识', '同名项目与隐私'],
  ['TC-053', 'unit', 'tests/m6-report.test.ts', 'TC-053 项目模型聚合沿用授权范围和未知项目', '项目模型汇总'],
  ['TC-054', 'e2e', 'tests/e2e/m6-analysis.spec.ts', 'TC-054 项目模型筛选及趋势下钻保持同一用量范围', '报表筛选下钻'],
  ['TC-055', 'unit', 'tests/m6-report.test.ts', 'TC-055 项目筛选 CSV 与页面同口径且文本安全', '项目 CSV'],
  ['TC-056', 'e2e', 'tests/e2e/m6-shell.spec.ts', 'TC-056 长报表右侧滚动时左侧导航保持固定', '固定左栏'],
  ['TC-057', 'e2e', 'tests/e2e/m6-shell.spec.ts', 'TC-057 窄窗口路径可见且下钻可从面包屑返回', '响应式路径'],
  ['TC-058', 'e2e', 'tests/e2e/m6-update.spec.ts', 'TC-058 登录后可直接发现检查更新入口', '更新入口'],
  ['TC-059', 'e2e', 'tests/e2e/m6-update.spec.ts', 'TC-059 新版坏包提示错误且重试后可重新检查', '更新状态与重试'],
  ['TC-060', 'e2e', 'tests/e2e/m6-settings.spec.ts', 'TC-060 设置分组完整且普通用户修改接口被拒绝', '集中设置与权限'],
  ['TC-061', 'e2e', 'tests/e2e/m6-settings.spec.ts', 'TC-061 缺少目录时诊断引导权限设置和重新扫描', '权限引导'],
  ['TC-062', 'unit', 'tests/m6-diagnostics.test.ts', 'TC-062 缺目录解析错待写完记录及未归属有独立诊断', '漏采诊断'],
  ['TC-063', 'unit', 'tests/m6-diagnostics.test.ts', 'TC-063 诊断摘要不包含原始路径正文与项目标识', '诊断隐私'],
  ['TC-064', 'unit', 'tests/m6-feedback.test.ts', 'TC-064 反馈仅显式提交且阻止路径密钥进入服务', '反馈预览与白名单'],
  ['TC-065', 'unit', 'tests/m6-feedback.test.ts', 'TC-065 反馈离线持久化重试幂等且管理读取需独立密钥', '反馈离线与幂等'],
  ['TC-066', 'e2e', 'tests/e2e/m6-admin.spec.ts', 'TC-066 管理员可看反馈列表而普通用户接口拒绝', '反馈管理权限'],
  ['TC-067', 'e2e', 'tests/e2e/m6-admin.spec.ts', 'TC-067 账号启停归属和采集状态随操作更新', '账号采集状态'],
  ['TC-068', 'unit', 'tests/m6-roles.test.ts', 'TC-068 首建固定 admin 且库内角色兼容旧约束', '固定超级管理员'],
  ['TC-069', 'unit', 'tests/m6-roles.test.ts', 'TC-069 普通管理员保留建户权限但不能改动固定 admin', '管理角色边界'],
  ['TC-070', 'unit', 'tests/m6-roles.test.ts', 'TC-070 旧库 admin 冲突显式处理且保留账号 ID 和哈希', '旧库迁移'],
  ['TC-071', 'e2e', 'tests/e2e/m6-admin.spec.ts', 'TC-071 固定 admin 创建管理员与普通用户且角色边界生效', '超级管理员界面'],
  ['TC-072', 'manual', '目标 Mac 文件权限授予与撤销', '使用独立测试账户及专用数据库，先拒绝 Token 读取会话目录并截图采集诊断未知状态；在系统设置手动授予完全磁盘访问权限，重启并重新扫描，截图恢复状态；再次撤销并确认回到未知。记录 macOS 版本、授权范围、命令和脱敏证据。'],
  ['TC-073', 'unit', 'tests/collector-fallback.test.ts', 'TC-073 Codex fallback 跨扫描替换与旧库修复保持幂等', 'Codex fallback 跨扫描归并'],
  ['TC-074', 'unit', 'tests/server-ownership.test.ts', 'TC-074 聚合上报拒绝跨设备跨用户覆盖并保留原快照', '聚合上报设备与用户归属授权回归'],
  ['TC-075', 'unit', 'tests/signed-release.test.ts', 'TC-075 签名发布预检与命令构造', '签名发布脚本预检与命令构造'],
  ['TC-076', 'integration', 'scripts/verify-auto-upgrade.mjs', 'TC-076 自动更新打包应用', '自动退出、替换和重启新版'],
  ['TC-077', 'unit', 'tests/coverage-window.test.ts', 'TC-077 管理员筛选覆盖不借用其他 owner 或全局 ready', '所选范围防假零子断言'],
  ['TC-078', 'unit', 'tests/coverage-window.test.ts', 'TC-078 时区边界和待核对窗口不伪造完整覆盖或同比', '时区与比较防假同比子断言'],
  ['TC-079', 'unit', 'tests/report-snapshot.test.ts', 'TC-079 查询后新增事实必须刷新快照才能导出相同事实集合', '报表快照与 CSV 一致'],
  ['TC-080', 'e2e', 'tests/e2e/overview-drilldown.spec.ts', 'TC-080 概览趋势继承时间工具并在面包屑返回后保留筛选与焦点', '概览趋势上下文下钻'],
  ['TC-081', 'e2e', 'tests/e2e/overview-drilldown.spec.ts', 'TC-081 同名模型按提供方下钻且筛选选项不混合', '模型提供方身份下钻'],
  ['TC-082', 'unit', 'tests/onboarding.test.ts', 'TC-082 四步按检测扫描归属和已确认首笔事实推进', '管理员四步引导与跳过重开'],
  ['TC-083', 'unit', 'tests/onboarding.test.ts', 'TC-083 普通用户只看本人状态且待核对事实不算首笔确认用量', '普通用户引导权限与未知状态'],
  ['TC-084', 'unit', 'tests/empty-state.test.ts', 'TC-084 未扫描权限格式筛选无匹配及已观测未知各给出独立行动且不造真零', '空状态保守分型与行动'],
  ['TC-085', 'unit', 'tests/m6-diagnostics.test.ts', 'TC-085 慢扫描真实处理数及解析失败修复重试', '真实扫描进展与重试'],
  ['TC-086', 'unit', 'tests/source-binding.test.ts', 'TC-086 预览双侧授权范围取消过期和在线确认清除旧归属', '来源重绑预览与授权清理'],
  ['TC-087', 'unit', 'tests/source-binding.test.ts', 'TC-087 停用旧归属仍可迁出事务故障回滚离线新快照覆盖旧队列', '重绑回滚与离线同步'],
  ['TC-088', 'unit', 'tests/service-state.test.ts', 'TC-088 内置默认与同地址显式配置重启仍保留来源并可切回', '服务配置来源连接授权协议与同步状态'],
  ['TC-091', 'e2e', 'tests/e2e/settings-copy.spec.ts', 'TC-091 遥测说明与疑似重叠报表及 CSV v2 状态一致', '遥测说明与调和口径一致'],
  ['TC-092', 'unit', 'tests/reconciliation.test.ts', 'TC-092 跨用户和不同会话遥测独立保留且同会话冲突不伪造总量', '本地与遥测归属和会话调和'],
  ['TC-093', 'unit', 'tests/reconciliation.test.ts', 'TC-093 报表明细和 CSV v2 同源逐组小计且时区边界不漏冲突', '报表明细与 CSV v2 调和'],
  ['TC-094', 'unit', 'tests/sync-reconciliation.test.ts', 'TC-094 服务 v2 清除旧聚合并保留冲突状态旧队列重算和权限边界', '服务上报协议 v2 与旧数据迁移']
];
const extraRuns = {
  'TC-077': [{ kind: 'e2e', file: 'tests/e2e/coverage-window.spec.ts', testName: 'TC-077 管理员切换用户和未归属时概览报表不显示假零' }],
  'TC-078': [{ kind: 'e2e', file: 'tests/e2e/coverage-window.spec.ts', testName: 'TC-078 只有待核对记录时保留已确认小计零而完整总量未知' }],
  'TC-082': [
    { kind: 'unit', file: 'tests/onboarding.test.ts', testName: 'TC-082 大量合成历史记录的引导状态响应保持可用' },
    { kind: 'e2e', file: 'tests/e2e/onboarding.spec.ts', testName: 'TC-082 管理员可跳过重开且四步随真实采集归属更新' }
  ],
  'TC-083': [{ kind: 'e2e', file: 'tests/e2e/onboarding.spec.ts', testName: 'TC-083 普通用户引导不显示他人进度且无权扫描归属' }],
  'TC-084': [{ kind: 'e2e', file: 'tests/e2e/empty-state.spec.ts', testName: 'TC-084 报表筛选无匹配保持覆盖未知并可清除筛选进入诊断' }],
  'TC-085': [
    { kind: 'unit', file: 'tests/m6-diagnostics.test.ts', testName: 'TC-085 取消等待当前文件提交且续扫不重复或上报残缺快照' },
    { kind: 'unit', file: 'tests/m6-diagnostics.test.ts', testName: 'TC-085 第二个工具取消不把首个工具成功误作完整扫描' },
    { kind: 'unit', file: 'tests/m6-diagnostics.test.ts', testName: 'TC-085 发现目录阶段取消后不读取任何记录文件' },
    { kind: 'unit', file: 'tests/m6-diagnostics.test.ts', testName: 'TC-085 文件持久化失败后事实与游标一起回滚并可续扫' },
    { kind: 'e2e', file: 'tests/e2e/empty-state.spec.ts', testName: 'TC-085 慢速合成扫描在诊断页显示中间进展且完成后清除' },
    { kind: 'e2e', file: 'tests/e2e/empty-state.spec.ts', testName: 'TC-085 取消显示未知状态且重新扫描继续完成' }
  ],
  'TC-086': [{ kind: 'e2e', file: 'tests/e2e/source-binding.spec.ts', testName: 'TC-086 草稿预览键盘取消与确认后权限转移' }],
  'TC-087': [{ kind: 'e2e', file: 'tests/e2e/source-binding.spec.ts', testName: 'TC-087 预览后重扫变化确认拒绝且界面恢复旧归属' }],
  'TC-088': [
    { kind: 'unit', file: 'tests/service-state.test.ts', testName: 'TC-088 离线拒权与旧协议独立于配置来源和本机覆盖' },
    { kind: 'unit', file: 'tests/service-state.test.ts', testName: 'TC-088 切换服务后旧成功修订版失效且新快照待传再确认' },
    { kind: 'unit', file: 'tests/service-state.test.ts', testName: 'TC-088 配置落盘失败保留旧身份且新配置不会拾取旧密钥' },
    { kind: 'unit', file: 'tests/service-state.test.ts', testName: 'TC-088 内置服务身份不符时不发送访问密钥' },
    { kind: 'unit', file: 'tests/service-state.test.ts', testName: 'TC-088 内置服务身份检查期间切换配置不覆盖新地址或发送旧密钥' },
    { kind: 'e2e', file: 'tests/e2e/service-state.spec.ts', testName: 'TC-088 服务配置认证协议待传和本机覆盖在界面并列且可重试' },
    { kind: 'e2e', file: 'tests/e2e/service-state.spec.ts', testName: 'TC-088 快照落盘失败时不切换服务配置' }
  ],
  'TC-091': [{ kind: 'unit', file: 'tests/reconciliation.test.ts',
    testName: 'TC-093 报表明细和 CSV v2 同源逐组小计且时区边界不漏冲突' }],
  'TC-023': [{ kind: 'unit', file: 'tests/report-snapshot.test.ts', testName: 'TC-023 CSV v2 待核对行的模型和项目名称仍转义公式' }],
  'TC-079': [{ kind: 'e2e', file: 'tests/e2e/report-snapshot.spec.ts', testName: 'TC-079 快速切换筛选时旧响应不覆盖且导出等待当前快照' }],
  'TC-093': [{ kind: 'e2e', file: 'tests/e2e/overlap-privacy.spec.ts', testName: 'TC-093 普通用户来源状态诊断和反馈附件不含其他账户数据' }],
  'TC-036': [{ kind: 'unit', file: 'tests/update-install.test.ts', testName: 'TC-036 自动安装目标选择、退出后替换和失败回滚' }],
  'TC-030': [{ kind: 'e2e', file: 'tests/e2e/trust.spec.ts', testName: 'TC-030 应用重启自动登录并在退出后撤销' }],
  'TC-032': [{ kind: 'unit', file: 'tests/next-server.test.ts', testName: 'TC-032 临时 CA 严格验证非回环服务与证书失败路径' }],
  'TC-038': [{ kind: 'e2e', file: 'tests/e2e/upload.spec.ts', testName: 'TC-038 应用扫描后自动上报到独立本机服务' }],
  'TC-010': [{ kind: app[0], file: app[1], testName: app[2] }],
  'TC-017': [{ kind: collector[0], file: collector[1], testName: '空目录、错误字段及不可读文件显示可辨认的状态' }],
  'TC-073': [{ kind: 'unit', file: 'tests/collector-fallback.test.ts', testName: 'TC-073 大会话无 fallback 时启动修复保持线性耗时' }],
  'TC-074': [
    { kind: 'unit', file: 'tests/server-ownership.test.ts', testName: 'TC-074 客户端加密保存设备令牌且撤销后须显式重新登记' },
    { kind: 'unit', file: 'tests/server-ownership.test.ts', testName: 'TC-074 切换服务器时不向新地址发送旧设备令牌' },
    { kind: 'unit', file: 'tests/next-sync.test.ts', testName: 'TC-074 管理员重新配置后可立即重试待传快照' }
  ],
  'TC-047': [
    { kind: 'unit', file: 'tests/next-server.test.ts', testName: 'TC-047 非回环 HTTPS 监听仍执行清单与上报鉴权' },
    { kind: 'unit', file: 'tests/next-server.test.ts', testName: 'TC-047 严格 TLS 下保护接口维持鉴权' }
  ],
  'TC-021': [
    { kind: app[0], file: app[1], testName: app[2] },
    { kind: 'unit', file: 'tests/report-pagination.test.ts', testName: 'TC-021 明细翻页不漏记录且筛选和用户权限贯穿每页' },
    { kind: 'e2e', file: 'tests/e2e/report-pagination.spec.ts', testName: 'TC-021 报表明细可翻到第二页且切换模型重置页码' }
  ]
};
export default cases.map(([id, kind, fileOrTitle, testNameOrSteps, title]) => kind === 'manual'
  ? { id, kind, title: fileOrTitle, steps: testNameOrSteps }
  : { id, kind, title, runs: [{ kind, file: fileOrTitle, testName: testNameOrSteps }, ...(extraRuns[id] || [])] });
